<?php

namespace Imie\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TeacherAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Imie\CoreBundle\Controller\TeacherAdminController();
        return $instance;
    }
}
